### ISSUE TITLE
LdesClient version materialiser should look to the eventstream to determine versionOf

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-Linked-Data-Interactions#500] opened 2024-02-16 16:06 UTC
Currently you have to configure the "versionOf" property when you enable the materializer for the LdesClient. This should not be necessary as this path is configured on the LdesServer Eventstream.

**Comment by jobulcke** [comment] 2024-03-28 14:32
Duplicate of #494

**Closed by jobulcke** 2024-03-28 14:32 UTC
Labels: enhancement
